---
title: "OneR"
output: html_document
---

[Holger K. von Jouanne-Diedrich's OneR package](https://cran.r-project.org/web/packages/OneR/vignettes/OneR.html)

https://archive.ics.uci.edu/ml/datasets/Mammographic+Mass

Attribute Information:
   1. BI-RADS assessment: 1 to 5 (ordinal)  
   2. Age: patient's age in years (integer)
   3. Shape: mass shape: round=1 oval=2 lobular=3 irregular=4 (nominal)
   4. Margin: mass margin: circumscribed=1 microlobulated=2 obscured=3 ill-defined=4 spiculated=5 (nominal)
   5. Density: mass density high=1 iso=2 low=3 fat-containing=4 (ordinal)
   6. Severity: benign=0 or malignant=1 (binominal)

```{r message=FALSE, warning=FALSE}
library(tidyverse)

data <- read.table("mammographic_masses.data.txt", sep = ",") %>%
  mutate(V2 = as.numeric(as.character(V2)),
         V6 = as.factor(V6))

data[data == "?"] <- NA
```

```{r}
length(which(is.na(data)))
```

```{r mds_plot, echo=FALSE, eval=FALSE}
# Multidimensional Scaling 
select(data, -6) %>%
  dist() %>%
  cmdscale %>%
  as.data.frame() %>%
  mutate(group = data$V6) %>%
  ggplot(aes(x = V1, y = V2, color = group)) +
    geom_point()
```

```{r fig.width=5, fig.height=3}
data %>%
  ggplot(aes(x = V6)) +
    geom_bar()
```

```{r warning=FALSE, message=FALSE}
# configure multicore
library(doParallel)
cl <- makeCluster(detectCores())
registerDoParallel(cl)

library(caret)
```

```{r}
set.seed(42)
index <- createDataPartition(data$V6, p = 0.7, list = FALSE)
train_data <- data[index, ]
test_data  <- data[-index, ]
```

<br>

Downloaded from CRAN.

```{r}
library(OneR)
```

```{r}
data <- train_data
data_1 <- bin(data, nbins = 5, method = "length")

data_2 <- bin(data, nbins = 5, method = "content")

data_3 <- bin(data, nbins = 2, method = "cluster")

data_4 <- optbin(formula = V6 ~., data = train_data, method = "logreg")

data_5 <- optbin(formula = V6 ~., data = train_data, method = "infogain")
```

```{r message=FALSE, warning=FALSE, fig.width=15, fig.height=3, echo=FALSE, eval=FALSE}
data %>%
  gather(x, y, V1:V5) %>%
  ggplot(aes(x = y, fill = V6)) +
    geom_bar() +
    facet_wrap(~ x, scales = "free", ncol = 5)
```

```{r message=FALSE, warning=FALSE, fig.width=15, fig.height=3, echo=FALSE, eval=FALSE}
data_1 %>%
  gather(x, y, V1:V5) %>%
  ggplot(aes(x = y, fill = V6)) +
    geom_bar() +
    facet_wrap(~ x, scales = "free", ncol = 5)
```

```{r message=FALSE, warning=FALSE, fig.width=15, fig.height=3, echo=FALSE, eval=FALSE}
data_2 %>%
  gather(x, y, V1:V5) %>%
  ggplot(aes(x = y, fill = V6)) +
    geom_bar() +
    facet_wrap(~ x, scales = "free", ncol = 5)
```

```{r message=FALSE, warning=FALSE, fig.width=15, fig.height=3, echo=FALSE, eval=FALSE}
data_3 %>%
  gather(x, y, V1:V5) %>%
  ggplot(aes(x = y, fill = V6)) +
    geom_bar() +
    facet_wrap(~ x, scales = "free", ncol = 5)
```

```{r message=FALSE, warning=FALSE, fig.width=15, fig.height=3, echo=FALSE, eval=FALSE}
data_4 %>%
  gather(x, y, V1:V5) %>%
  ggplot(aes(x = y, fill = V6)) +
    geom_bar() +
    facet_wrap(~ x, scales = "free", ncol = 5)
```

```{r message=FALSE, warning=FALSE, fig.width=15, fig.height=3, echo=FALSE, eval=FALSE}
data_5 %>%
  gather(x, y, V1:V5) %>%
  ggplot(aes(x = y, fill = V6)) +
    geom_bar() +
    facet_wrap(~ x, scales = "free", ncol = 5)
```

```{r}
# 5 bins, default method length
model_1 <- OneR(formula = V6 ~., data = data_1, verbose = FALSE)

# 5 bins, method content
model_2 <- OneR(formula = V6 ~., data = data_2, verbose = FALSE)

# 2 bins, method cluster
model_3 <- OneR(formula = V6 ~., data = data_3, verbose = FALSE)

# optimal bin number logistic regression
model_4 <- OneR(formula = V6 ~., data = data_4, verbose = FALSE)

# optimal bin number information gain
model_5 <- OneR(formula = V6 ~., data = data_5, verbose = FALSE)
```

```{r}
eval_model(predict(model_1, test_data), test_data$V6)
eval_model(predict(model_2, test_data), test_data$V6)
eval_model(predict(model_3, test_data), test_data$V6)
eval_model(predict(model_4, test_data), test_data$V6)
eval_model(predict(model_5, test_data), test_data$V6)
```

```{r}
summary(model)
```

```{r fig.width=10, fig.height=5}
plot(model)
```


```{r}
prediction_prob <- predict(model, test_data, type = "prob")
```

---

```{r}
sessionInfo()
```

