---
title: "Data Science for Business - Time Series Forcasting Part 1: EDA & Simple Models"
author: "Dr. Shirin Glander"
date: "May 22, 2017"
output: html_document
---

https://cran.r-project.org/web/packages/timekit/index.html


http://archive.ics.uci.edu/ml/datasets/Online+Retail

```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(tidyquant)

library(modelr)
options(na.action = na.warn)

library(timekit)
library(broom)

library(gridExtra)
library(grid)
```

```{r cache=TRUE}
retail <- read_csv("OnlineRetail.csv",
                   col_types = cols(
  InvoiceNo = col_character(),
  StockCode = col_character(),
  Description = col_character(),
  Quantity = col_integer(),
  InvoiceDate = col_datetime("%m/%d/%Y %H:%M"),
  UnitPrice = col_double(),
  CustomerID = col_integer(),
  Country = col_character()
)) %>%
  mutate(day = parse_date(format(InvoiceDate, "%Y-%m-%d")),
         time = parse_time(format(InvoiceDate, "%H:%M")),
         month = format(InvoiceDate, "%m"),
         income = Quantity * UnitPrice,
         income_return = ifelse(Quantity >= 0, "income", "return"))

retail
```

<br>

## Visual exploration

```{r fig.width=10, fig.height=4}
p1 <- retail %>%
  filter(Country == "United Kingdom") %>%
  ggplot(aes(x = Country, fill = income_return)) +
    geom_bar() +
    scale_fill_manual(values = palette_light()) +
    theme_tq() +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
    guides(fill = FALSE)

p2 <- retail %>%
  filter(Country != "United Kingdom") %>%
  ggplot(aes(x = Country, fill = income_return)) +
    geom_bar() +
    scale_fill_manual(values = palette_light()) +
    theme_tq() +
    theme(legend.position = "right") +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

grid.arrange(p1, p2, widths = c(0.2, 0.8))
```

```{r fig.width=8, fig.height=3}
retail %>%
  ggplot(aes(x = day, color = income_return)) +
    geom_freqpoly(bins = 100, size = 1, alpha = 0.6) +
    scale_color_manual(values = palette_light()) +
    theme_tq() +
    labs(title = "Number of purchases/returns per day")
```

```{r fig.width=8, fig.height=3}
retail %>%
  ggplot(aes(x = day, y = ..density.., color = income_return)) +
    geom_freqpoly(size = 1, alpha = 0.7, bins = 100) +
    scale_color_manual(values = palette_light()) +
    theme_tq() +
    labs(title = "Density of purchases/returns per day")
```

```{r fig.width=8, fig.height=3}
retail %>%
  group_by(day, income_return) %>%
  summarise(sum_income = sum(income)) %>%
  ggplot(aes(x = day, y = sum_income, color = income_return)) +
    geom_ref_line(h = 0) +
    geom_line(size = 1, alpha = 0.6) +
    scale_color_manual(values = palette_light()) +
    theme_tq() +
    labs(title = "Income from purchases/returns per day")
```

```{r fig.width=8, fig.height=3}
retail %>%
  group_by(time, income_return) %>%
  summarise(sum_income = sum(income)) %>%
  ggplot(aes(x = time, y = sum_income, color = income_return)) +
    geom_ref_line(h = 0) +
    geom_line(size = 1, alpha = 0.6) +
    scale_color_manual(values = palette_light()) +
    theme_tq() +
    labs(title = "Income from purchases/returns per time of day")
```

```{r fig.width=8, fig.height=5}
retail %>%
  ggplot(aes(x = time, y = day)) +
    stat_binhex(alpha = 0.8, bins = 25, color = "white") +
    scale_fill_gradientn(colours = c(palette_light()[[1]], palette_light()[[2]])) +
    theme_tq() +
    theme(legend.position = "right") +
    labs(title = "Purchases/returns per day and time")
```

```{r fig.width=8, fig.height=5}
retail %>%
  mutate(day2 = format(InvoiceDate, "%d")) %>%
  group_by(month, day2) %>%
  summarise(sum_income = sum(income)) %>%
  ggplot(aes(x = month, y = day2, fill = sum_income)) +
    geom_tile(alpha = 0.8, color = "white") +
    scale_fill_gradientn(colours = c(palette_light()[[1]], palette_light()[[2]])) +
    theme_tq() +
    theme(legend.position = "right") +
    labs(title = "Net income per month and day")
```

<br>

## Modeling

```{r}
range(retail$day)

retail<- retail %>%
  mutate(model = ifelse(day <= "2011-11-01", "train", "test"))

rep_customer <- retail %>%
  group_by(day, CustomerID) %>%
  summarise(n = n()) %>%
  mutate(repeat_customer = ifelse(duplicated(CustomerID), TRUE, FALSE))

length(which(rep_customer$repeat_customer == TRUE))

country_purch <- retail %>%
  mutate(Country2 = ifelse(Country == "United Kingdom", "uk", "other_country")) %>%
  group_by(day, Country2) %>%
  summarise(n = n()) %>%
  spread(key = Country2, value = n)

n <- retail %>%
  group_by(day, income_return) %>%
  summarise(n = n()) %>%
  spread(key = income_return, value = n)

retail_p_day <- retail %>%
  group_by(day) %>%
  summarise(sum_income = sum(income),
            mean_income = mean(income),
            sum_income_purch = sum(income[income >= 0]),
            sum_loss_return = sum(income[income < 0]),
            mean_income_purch = mean(income[income >= 0]),
            mean_loss_return = mean(income[income < 0]),
            
            sum_quantity = sum(Quantity),
            mean_quantity = mean(Quantity),
            sum_quantity_purch = sum(Quantity[Quantity >= 0]),
            sum_loss_return = sum(Quantity[Quantity < 0]),
            mean_quantity_purch = mean(Quantity[Quantity >= 0]),
            mean_loss_return = mean(Quantity[Quantity < 0]),
            
            mean_unit_price = mean(UnitPrice)) %>%
  left_join(n, by = "day") %>%
  left_join(country_purch, by = "day") %>%
  left_join(distinct(select(retail, day, month, model)), by = "day") %>%
  mutate(season = ifelse(month %in% c("03", "04", "05"), "spring",
                         ifelse(month %in% c("06", "07", "08"), "summer",
                                ifelse(month %in% c("09", "10", "11"), "fall", "winter"))))
```

```{r fig.width=8, fig.height=6}
retail_p_day %>%
  gather(x, y, sum_income:mean_income) %>%
  ggplot(aes(x = day, y = y, color = model)) +
    facet_wrap(~ x, ncol = 1, scales = "free") +
    geom_point(alpha = 0.5) +
    geom_line(alpha = 0.5) +
    scale_color_manual(values = palette_light()) +
    theme_tq()
```

```{r fig.width=8, fig.height=6}
retail_p_day %>%
  gather(x, y, sum_quantity:mean_quantity) %>%
  ggplot(aes(x = day, y = y, color = model)) +
    facet_wrap(~ x, ncol = 1, scales = "free") +
    geom_point(alpha = 0.5) +
    geom_line(alpha = 0.5) +
    scale_color_manual(values = palette_light()) +
    theme_tq()
```

```{r}
train <- filter(retail_p_day, model == "train") %>%
  select(sum_income, mean_unit_price, income, return, other_country, uk, season)
```

```{r warning=FALSE, message=FALSE}
lm_train <- lm(sum_income ~ ., data = train)

test <- filter(retail_p_day, model == "test") %>%
  add_predictions(lm_train) %>%
  add_residuals(lm_train)
```

```{r}
test %>%
  ggplot(aes(x = sum_income, y = pred)) +
    geom_smooth(method = "lm") +
    geom_abline() +
    geom_point(alpha = 0.5) +
    scale_color_manual(values = palette_light()) +
    theme_tq()
```

```{r}
test %>%
  gather(x, y, sum_income, pred) %>%
  ggplot(aes(x = day, y = y, color = x)) +
    geom_smooth(method = "lm") +
    geom_point(alpha = 0.5) +
    geom_line(alpha = 0.5) +
    scale_color_manual(values = palette_light()) +
    theme_tq()
```

```{r}
data.frame(day = c(retail_p_day$day, test$day),
           sum_income = c(retail_p_day$sum_income, test$pred),
           group = c(rep("original", nrow(retail_p_day)), rep("prediction", nrow(test)))) %>%
  ggplot(aes(x = day, y = sum_income, color = group)) +
    geom_point(alpha = 0.5) +
    geom_line() +
    scale_color_manual(values = palette_light()) +
    theme_tq()
```

```{r}
ggplot(test, aes(sum_income, resid)) + 
  geom_ref_line(h = 0) +
  geom_point(alpha = 0.5) +
  scale_color_manual(values = palette_light()) +
  theme_tq()
```






