---
title: "Gran Canaria"
author: "Dr. Shirin Glander"
date: '`r Sys.Date()`'
output: html_document
---

```{r fig.width = 6, fig.height = 5, fig.align = "center"}
library(ggplot2)
library(ggmap)

map <- get_map(c(lon = -15.59972, lat = 27.965), zoom = 10)
```

### GPS tracks

https://shiring.github.io/maps/gpx/2016/10/16/roadtrip2016

```{r eval=FALSE, echo=TRUE, message=FALSE, warning=FALSE, cache=TRUE}
library(XML)

myfiles <- list.files(path = "~/Documents/Github/Takeout_2017_March", full.names = TRUE)
myfiles <- myfiles[grep(".gpx", myfiles)]

for (i in 1:length(myfiles)) {
  tryCatch({
    pfile <- htmlTreeParse(myfiles[i], useInternalNodes = T)

  }, error = function(e){cat("ERROR\n")})

  if (exists("pfile")) {
    # Get all elevations, times and coordinates via the respective xpath
    elevations <- as.numeric(as.character(xpathSApply(pfile, path = "//trkpt/ele", xmlValue)))
    times <- xpathSApply(pfile, path = "//trkpt/time", xmlValue)
    coords <- xpathSApply(pfile, path = "//trkpt", xmlAttrs)
    # Extract latitude and longitude from the coordinates
    lats <- as.numeric(as.character(coords["lat",]))
    lons <- as.numeric(as.character(coords["lon",]))
    # Put everything in a dataframe and get rid of old variables
    geodf <- data.frame(lat = lats, lon = lons, ele = elevations, time = times)

    if (i == 1) {
      geodata <- geodf
      } else {
      geodata <- rbind(geodata, geodf)
    }
  }
  rm(pfile)
}

geodata_all <- geodata

# Transforming the time column
geodata_all$time <- as.character(strptime(geodata_all$time, format = "%Y-%m-%dT%H:%M:%SZ"))

# ordering by date
library(dplyr)
geodata_all <- arrange(geodata_all, time)

geodata_gc <- filter(geodata_all, lat < 28.5 & lat > 27.5) %>%
  filter(lon > -16 & lon < -15)
```

```{r echo=FALSE, eval=FALSE}
save(geodata_gc, file = "geodata_gc.RData")
```

```{r echo=FALSE}
load("geodata_gc.RData")
```

<br>

### GPX hiking tracks

https://www.rother.de/rother%20wanderf%FChrer-gran%20canaria-4459.htm

	Rother Wanderführer
7. Auflage 2016

```{r eval=FALSE, echo=TRUE, message=FALSE, warning=FALSE, cache=TRUE}
library(plotKML)

myfiles <- list.files(path = "~/Documents/Github/Takeout_2017_March/hiking", full.names = TRUE)
myfiles <- myfiles[grep(".gpx", myfiles)]

for (i in 1:length(myfiles)) {
  t <- readGPX(myfiles[i])
  
  geodf <- data.frame(lon = t$tracks[[1]][[1]]$lon,
                      lat = t$tracks[[1]][[1]]$lat,
                      ele = t$tracks[[1]][[1]]$ele,
                      tour = names(t$tracks[[1]]))

    if (i == 1) {
      geodata <- geodf
      } else {
      geodata <- rbind(geodata, geodf)
    }
  rm(pfile)
}

geodata_tracks <- geodata
```

```{r echo=FALSE, eval=FALSE}
save(geodata_tracks, file = "geodata_tracks.RData")
```

```{r echo=FALSE}
load("geodata_tracks.RData")
```

<br>

### Google location history

https://shiring.github.io/maps/2016/12/30/Standortverlauf_post

```{r eval=FALSE, echo = TRUE, message = FALSE, warning = FALSE, cache=FALSE}
library(jsonlite)
system.time(x <- fromJSON("~/Documents/Github/Takeout_2017_March/Standortverlauf.json"))
```

```{r eval=FALSE, echo = TRUE, message = FALSE, warning = FALSE, cache=FALSE}
# extracting the locations dataframe
loc = x$locations

# converting time column from posix milliseconds into a readable time scale
loc$time = as.POSIXct(as.numeric(x$locations$timestampMs)/1000, origin = "1970-01-01")

# converting longitude and latitude from E7 to GPS coordinates
loc$lat = loc$latitudeE7 / 1e7
loc$lon = loc$longitudeE7 / 1e7

# keep only data from Gran Canaria: http://www.travelmath.com/island/Gran+Canaria
# 27° 57' 54" N / 15° 35' 59" W
# convert to decimal: http://www.rapidtables.com/convert/number/degrees-minutes-seconds-to-degrees.htm
# 27.965 & 15.59972
library(dplyr)
loc_gc <- filter(loc, lat < 28.5 & lat > 27.5) %>%
  filter(lon > -16 & lon < -15)
```

```{r echo=FALSE, eval=FALSE}
save(loc_gc, file = "loc_gc.RData")
```

```{r echo=FALSE}
load("loc_gc.RData")
```

---

```{r}
data_combined <- data.frame(lat = c(geodata_gc$lat, loc_gc$lat, geodata_tracks$lat),
                            lon = c(geodata_gc$lon, loc_gc$lon, geodata_tracks$lon),
                            ele = c(geodata_gc$ele, loc_gc$altitude, geodata_tracks$ele),
                            track = c(rep("GPS", nrow(geodata_gc)), rep("Google", nrow(loc_gc)), rep("Hiking", nrow(geodata_tracks))))
```

```{r fig.width = 10, fig.height = 10, fig.align = "center"}
ggmap(map) + 
  geom_point(data = data_combined, aes(x = lon, y = lat, color = track), alpha = 0.3)
```

```{r fig.width = 10, fig.height = 10, fig.align = "center"}
ggmap(map) + 
  geom_point(data = data_combined, aes(x = lon, y = lat, color = ele), alpha = 0.3)
```
