---
title: "WebGL"
author: "Dr. Shirin Glander"
date: "March 29, 2017"
output: html_document
---

```{r fig.width=10, fig.height=10}
library(maptools)
library(raster)
srtm <- getData("SRTM", lon=-15.59972, lat=27.965)
```

```{r message=FALSE, warning=FALSE}
library(rgdal)
library(rasterVis)
library(rgl)
library(htmlwidgets)
```

```{r 3dplot, echo=FALSE, eval=FALSE, fig.width=20, fig.height=20, webgl=TRUE}
library(knitr)
knit_hooks$set(webgl = hook_webgl)

open3d() # Open a new RGL device
plot3D(srtm)
#writeWebGL(dir = "webGL", filename = file.path(getwd(), "index.html"), width = 1000, height = 1000)
#browseURL(paste("file://", writeWebGL(dir=file.path(getwd(), "webGL"), width=1000), sep=""))
#movie3d(spin3d(axis = c(0, 0, 1)), duration = 3, dir = getwd(), clean = TRUE)
```

```{r }
options(rgl.printRglwidget = TRUE)

open3d()
plot3D(srtm)

open3d()
plot3D(srtm)
rglscene <- scene3d()
# render the saved rgl scene as widget in the markdown page
rglwidget(rglscene,webGLoptions = list(preserveDrawingBuffer = FALSE))
```

```{r}
rgl.close()
```

