---
title: "OneR"
output: html_document
---

I want to test the package on a difficult dataset, the food_world_cup data from fivethirty eight, that I tried to predict in an earlier post but which was difficult to handle because of the many NAs and unbalanced class distributions in it.

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(fivethirtyeight)

food_world_cup[food_world_cup == "N/A"] <- NA
food_world_cup <- apply(food_world_cup, 2, function(x) as.factor(x)) %>%
  as.data.frame()
```

```{r warning=FALSE, message=FALSE}
set.seed(42)
train_data <- sample_frac(food_world_cup, 0.7)
test_data  <- filter(food_world_cup, !respondent_id %in% train_data$respondent_id)
```

```{r}
rbind(data.frame(train_data, 
                 group = "train"),
      data.frame(test_data,
                 group = "test")) %>%
  ggplot(aes(x = france, fill = group)) +
  geom_bar(position = "dodge") +
  facet_wrap(~ group, ncol = 2, scales = "free")
```

```{r}
library(OneR)

model_france <- OneR(formula = france ~., data = train_data[, -1], verbose = TRUE)
```

```{r}
summary(model_france)
```

```{r}
plot(model_france)
```

```{r}
prediction <- predict(model_france, test_data)
```

```{r}
eval_model(prediction, test_data)
```

